 version: '3.4'

 services:
   node-hello:
     image: node-hello
     build: .
     environment:
       NODE_ENV: development
     ports:
       - 3000
       - 8888:80
     command: node --inspect=0.0.0.0:9229 ./bin